### ISSUE TITLE
ποτέ ίδιο id!!!!!!

### ISSUE THREAD

**Issue by tmanolat** [pboviatsi/crud-project#3]
https://github.com/pboviatsi/crud-project/blob/8894df5081da5144865fa72fd8175aa7ebfd0e6b/Client/src/components/routePage/EditProduct.js#L100

https://softwareengineering.stackexchange.com/questions/127178/two-html-elements-with-same-id-attribute-how-bad-is-it-really

**Comment by pboviatsi** [comment]
ειναι ιδιο γιατι ειναι id απο το material-table, αλλαζει την εμφανιση του πεδίου

**Comment by tmanolat** [comment]
μα απαγορεύεται να έχουμε το ίδιο element id στην html
`id="standard-helperText"`
δες το link παραπάνω - είναι αξίωμα

εκτός κι αν δεν κατάλαβα καλα

**Comment by tmanolat** [comment]
με ποιο commit έκλεισε?
πρεπει να το βαζουμε στο github

**Comment by pboviatsi** [comment]
Αυτό είναι το commit https://github.com/pboviatsi/crud-project/commit/748955923a2e5f357354ee776dc0c4965fce52f4 (καταλαθος δεν έβαλα κενό αναμεσα τους)
