### ISSUE TITLE
δες όλα του Σωκράτη

### ISSUE THREAD

**Issue by tmanolat** [pboviatsi/crud-project#4]
https://github.com/saznaouridis/react_project_2/issues

**Comment by pboviatsi** [comment]
https://github.com/pboviatsi/crud-project/commit/8d1de3ddc04693c0107a39cd5a67115973c19199  https://github.com/pboviatsi/crud-project/commit/913edb352bb4a0ceafb0aea11e8dbcc048f4a86e
